name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Run tests
      run: |
        xcodebuild \
          -scheme "hsluv-objc" \
          -destination "platform=macOS,arch=x86_64" \
          -enableCodeCoverage YES \
          CODE_SIGNING_REQUIRED=NO \
          test 